/* tslint:disable */
/* eslint-disable */
/**
 * miraculous_kingdom
 * Miraculous Kingdom public api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClassListDetailedResponse,
} from '../models/index';
import {
    ClassListDetailedResponseFromJSON,
    ClassListDetailedResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class ClassesApi extends runtime.BaseAPI {

    /**
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassListDetailedResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/classes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassListDetailedResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassListDetailedResponse> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

}
