
version: '3'

services:
  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $DB_USERNAME
      - --pass
      - $DB_PASSWORD
    image: surrealdb/surrealdb:latest
    ports:
      - 8080:8000
    volumes:
      - ./mk_surrealdb/migrations.surql:/migrations.surql

