
version: '3'

services:
  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASS
    image: surrealdb/surrealdb:latest
    ports:
      - 3100:8000
    volumes:
      - ./mk_surrealdb/migrations.surql:/migrations.surql

