version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mk_mongo
    ports:
      - "8100:27017"
    volumes:
      - mongodb_data:/data/db
      - ./miraculous-kingdom-self-server/mongo-seed:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mk2023!
      - MONGO_INITDB_DATABASE=mkdb

  api:
    #image: adamkali/miraculous-kingdom-api:0.2.0
    build: ./miraculous-kingdom-self-server
    container_name: mk-api
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
    environment:
      - RUST_LOG=info
    volumes:
      - ./miraculous-kingdom-self-server/certs:/working
  
        #app:
        #  build:
        #    context: ./miraculous-kingdom
        #    dockerfile: Dockerfile
        #  container_name: mk_app
        #  ports:
        #    - "80:80"
        #  depends_on:
        #    - api

volumes:
  mongodb_data:
