version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mk_mongo
    ports:
      - "8100:27017"
    volumes:
      - mongodb_data:/data/db
      - ./miraculous-kingdom-self-server/mongo-seed:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mk2023!
      - MONGO_INITDB_DATABASE=mkdb

  api:
    build: ./miraculous-kingdom-self-server
    container_name: api
    ports:
      - "8050:8050"
      - "8500:8500"
    depends_on:
      - mongodb
    environment:
      - RUST_LOG=info
    volumes:
      - ./miraculous-kingdom-self-server/certs:/app/certs

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./miraculous-kingdom-self-server/certs:/etc/nginx/certs
    depends_on:
      - api

volumes:
  mongodb_data:

