import "./globals.css";

import { FaGithubSquare, FaDocker, FaRedditSquare } from "react-icons/fa";
import { BsBookFill } from "react-icons/bs";
import Link from "next/link";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="min-h-screen min-w-full bg-gradient-to-tr from-blue-600 from-10% via-slate-200 to-pink-600 to-100% dark:from-blue-900 dark:via-black dark:to-pink-800 ">
                <nav className="top-8 m-8 grid grid-cols-6 rounded-full bg-slate-200 p-4 dark:bg-black">
                    <div>
                        <div className="text-3xl font-bold text-pink-600 dark:text-pink-400">
                            Miraculous Kingdom
                        </div>
                    </div>
                    <div className="col-span-4">
                        <div className="flex flex-row justify-center text-3xl font-bold text-blue-800 dark:text-blue-600">
                            <Link
                                className="flex flex-row items-center align-middle"
                                href="/rules"
                            >
                                <BsBookFill className="mr-8" />
                                <div className="">Rules</div>
                            </Link>
                        </div>
                    </div>
                    <div>
                        <div className="flex flex-row justify-end text-3xl font-bold text-blue-800 dark:text-blue-600">
                            <Link
                                className="mr-16"
                                href="https://github.com/adamkali/MiraculousKingdom"
                            >
                                <FaGithubSquare />
                            </Link>
                            <Link className="mr-16" href="/">
                                <FaDocker />
                            </Link>
                            <Link className="mr-16" href="/">
                                <FaRedditSquare />
                            </Link>
                        </div>
                    </div>
                </nav>
                <div className="flex flex-col items-center h-fit pb-12">
                    {children}
                </div>
            </body>
        </html>
    );
}
