FROM node:19-alpine as build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and yarn.lock files to the working directory
COPY . . 

# Install the dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the app's source code to the working directory
RUN yarn upgrade
RUN yarn build

FROM node:19-alpine3.16

WORKDIR /app
COPY --from=build /app .


ENV HOST=0.0.0.0
EXPOSE 4173
CMD ["yarn","run", "preview","--", "--host", "0.0.0.0"]


