/* tslint:disable */
/* eslint-disable */
/**
 * miraculous_kingdom
 * Miraculous Kingdom public api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClassResponse } from './ClassResponse';
import {
    ClassResponseFromJSON,
    ClassResponseFromJSONTyped,
    ClassResponseToJSON,
    ClassResponseToJSONTyped,
} from './ClassResponse';

/**
 * 
 * @export
 * @interface ClassListDetailedResponse
 */
export interface ClassListDetailedResponse {
    /**
     * 
     * @type {Array<ClassResponse>}
     * @memberof ClassListDetailedResponse
     */
    data?: Array<ClassResponse> | null;
    /**
     * 
     * @type {string}
     * @memberof ClassListDetailedResponse
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClassListDetailedResponse
     */
    nextLink?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ClassListDetailedResponse
     */
    successful: boolean;
}

/**
 * Check if a given object implements the ClassListDetailedResponse interface.
 */
export function instanceOfClassListDetailedResponse(value: object): value is ClassListDetailedResponse {
    if (!('successful' in value) || value['successful'] === undefined) return false;
    return true;
}

export function ClassListDetailedResponseFromJSON(json: any): ClassListDetailedResponse {
    return ClassListDetailedResponseFromJSONTyped(json, false);
}

export function ClassListDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassListDetailedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ClassResponseFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'nextLink': json['next_link'] == null ? undefined : json['next_link'],
        'successful': json['successful'],
    };
}

export function ClassListDetailedResponseToJSON(json: any): ClassListDetailedResponse {
    return ClassListDetailedResponseToJSONTyped(json, false);
}

export function ClassListDetailedResponseToJSONTyped(value?: ClassListDetailedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ClassResponseToJSON)),
        'message': value['message'],
        'next_link': value['nextLink'],
        'successful': value['successful'],
    };
}

