/* tslint:disable */
/* eslint-disable */
/**
 * miraculous_kingdom
 * Miraculous Kingdom public api
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassResponse
 */
export interface ClassResponse {
    /**
     * 
     * @type {string}
     * @memberof ClassResponse
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ClassResponse
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof ClassResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ClassResponse
     */
    name: string;
}

/**
 * Check if a given object implements the ClassResponse interface.
 */
export function instanceOfClassResponse(value: object): value is ClassResponse {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ClassResponseFromJSON(json: any): ClassResponse {
    return ClassResponseFromJSONTyped(json, false);
}

export function ClassResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'displayName': json['display_name'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function ClassResponseToJSON(json: any): ClassResponse {
    return ClassResponseToJSONTyped(json, false);
}

export function ClassResponseToJSONTyped(value?: ClassResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'display_name': value['displayName'],
        'id': value['id'],
        'name': value['name'],
    };
}

