// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Clock } from './clock';
import { MightRequirement } from './might-requirement';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class Ability extends APIModel {
    ability_clock: Clock;
    ability_desc: string;
    ability_name: string;
    ability_unlock: MightRequirement;

    constructor(options?: APIModelOptions) {
        super(Ability.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "ability_clock", type: "Clock" },
            { name: "ability_desc", type: "string" },
            { name: "ability_name", type: "string" },
            { name: "ability_unlock", type: "MightRequirement" }
        ];
    }
}




