// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Ability } from './ability';
import { CharacterState } from './character-state';
import { Class } from './class';
import { Clock } from './clock';
import { Might } from './might';
import { ObjectId } from './object-id';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class Character extends APIModel {
    /**
    * The character\'s abilities.
    */
    abilities: Array<Ability>;
    char_class: Class;
    /**
    * The character\'s clocks.
    */
    char_clocks: Array<Clock>;
    char_might: Might;
    /**
    * The name of the character.
    */
    char_name: string;
    char_state: CharacterState;
    game: ObjectId;
    /**
    * A secret lock to the character.
    */
    secret: string;

    constructor(options?: APIModelOptions) {
        super(Character.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "abilities", type: "Array<Ability>" },
            { name: "char_class", type: "Class" },
            { name: "char_clocks", type: "Array<Clock>" },
            { name: "char_might", type: "Might" },
            { name: "char_name", type: "string" },
            { name: "char_state", type: "CharacterState" },
            { name: "game", type: "ObjectId" },
            { name: "secret", type: "string" }
        ];
    }
}




