// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum ClassEnum {
    WarGeneral = 'WarGeneral',
    Aficianado = 'Aficianado',
    Researcher = 'Researcher',
    Cardinal = 'Cardinal',
    SpyMaster = 'SpyMaster',
    Diplomat = 'Diplomat',
    Merchant = 'Merchant',
    Prince = 'Prince'
}



