// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Ability } from './ability';
import { ClassEnum } from './class-enum';
import { MongodbBsonOidObjectId } from './mongodb-bson-oid-object-id';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class Class extends APIModel {
    class_abilities: Array<Ability>;
    class_desc: string;
    class_enum: ClassEnum;
    class_id: MongodbBsonOidObjectId;
    class_name: string;
    class_perks: string;

    constructor(options?: APIModelOptions) {
        super(Class.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "class_abilities", type: "Array<Ability>" },
            { name: "class_desc", type: "string" },
            { name: "class_enum", type: "ClassEnum" },
            { name: "class_id", type: "MongodbBsonOidObjectId" },
            { name: "class_name", type: "string" },
            { name: "class_perks", type: "string" }
        ];
    }
}




