// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Class } from './class';
import { Progress } from './progress';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class ClassDetailedResponse extends APIModel {
    code: number;
    data: Class;
    message: string;
    success: Progress;

    constructor(options?: APIModelOptions) {
        super(ClassDetailedResponse.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "code", type: "number" },
            { name: "data", type: "Class" },
            { name: "message", type: "string" },
            { name: "success", type: "Progress" }
        ];
    }
}




