// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class Clock extends APIModel {
    clock_conf: boolean;
    clock_desc: string;
    clock_duration: number;
    clock_name: string;
    clock_remaining: number;

    constructor(options?: APIModelOptions) {
        super(Clock.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "clock_conf", type: "boolean" },
            { name: "clock_desc", type: "string" },
            { name: "clock_duration", type: "number" },
            { name: "clock_name", type: "string" },
            { name: "clock_remaining", type: "number" }
        ];
    }
}




