// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class GameInfo extends APIModel {
    game_chars: Array<string>;
    game_name: string;
    game_ruler: string;

    constructor(options?: APIModelOptions) {
        super(GameInfo.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "game_chars", type: "Array<string>" },
            { name: "game_name", type: "string" },
            { name: "game_ruler", type: "string" }
        ];
    }
}




