// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MightEnum } from './might-enum';
import { RollTier } from './roll-tier';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class MightRequirement extends APIModel {
    might: MightEnum;
    roll_tier: RollTier;
    unlock: number;

    constructor(options?: APIModelOptions) {
        super(MightRequirement.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "might", type: "MightEnum" },
            { name: "roll_tier", type: "RollTier" },
            { name: "unlock", type: "number" }
        ];
    }
}




