// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MightStat } from './might-stat';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class Might extends APIModel {
    might_culture: MightStat;
    might_diplomacy: MightStat;
    might_espionage: MightStat;
    might_military: MightStat;
    might_religion: MightStat;
    might_science: MightStat;

    constructor(options?: APIModelOptions) {
        super(Might.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "might_culture", type: "MightStat" },
            { name: "might_diplomacy", type: "MightStat" },
            { name: "might_espionage", type: "MightStat" },
            { name: "might_military", type: "MightStat" },
            { name: "might_religion", type: "MightStat" },
            { name: "might_science", type: "MightStat" }
        ];
    }
}




