// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClassEnum } from './class-enum';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class NewCharacter extends APIModel {
    char_class: ClassEnum;
    /**
    * The character\'s might.
    */
    char_might: { [key: string]: number; };
    /**
    * The name of the character.
    */
    char_name: string;
    /**
    * A secret lock to the character for getting the character.
    */
    secret: string;

    constructor(options?: APIModelOptions) {
        super(NewCharacter.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "char_class", type: "ClassEnum" },
            { name: "char_might", type: "{ [key: string]: number; }" },
            { name: "char_name", type: "string" },
            { name: "secret", type: "string" }
        ];
    }
}




