// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Ability } from './ability';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class RewardTypesOneOf extends APIModel {
    Ability: Ability;

    constructor(options?: APIModelOptions) {
        super(RewardTypesOneOf.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "Ability", type: "Ability" }
        ];
    }
}




