// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Ability } from './ability';
import { RewardTypesOneOf } from './reward-types-one-of';
import { RewardTypesOneOf1 } from './reward-types-one-of1';

/**
 * @type RewardTypes
 * @export
 */
export type RewardTypes = RewardTypesOneOf | RewardTypesOneOf1;



