// tslint:disable
/**
 * miraculous-kingdom-self-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ObjectId } from './object-id';
import { RewardTypes } from './reward-types';

// tslint:disable
import { APIModel, APIModelOptions, AttributeMapItem } from "../base";

export class Season extends APIModel {
    event_desc: string;
    event_id: ObjectId;
    /**
    * The amount of turns the Character to the left of the ruler must take in order to go to the new season.
    */
    event_length: number;
    event_name: string;
    event_reward: RewardTypes;

    constructor(options?: APIModelOptions) {
        super(Season.attributeTypeMap, options);
    }

    static get attributeTypeMap(): Array<AttributeMapItem> {
        return [
            { name: "event_desc", type: "string" },
            { name: "event_id", type: "ObjectId" },
            { name: "event_length", type: "number" },
            { name: "event_name", type: "string" },
            { name: "event_reward", type: "RewardTypes" }
        ];
    }
}




