version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mk_mongo
    ports:
      - "8100:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mk2023!
      - MONGO_INITDB_DATABASE=mkdb

        #  api:
        #    build: .
        #    container_name: api
        #    ports:
        #      - "8050:3000"
        #    depends_on:
        #      - mongodb
        #
        #  nginx:
        #    image: nginx:latest
        #    container_name: nginx
        #    ports:
        #      - "8000:80"
        #    volumes:
        #      - ./nginx.conf:/etc/nginx/nginx.conf
        #    depends_on:
        #      - api

volumes:
  mongodb_data:

